# Generated by Django 5.1.1 on 2024-09-09 15:49

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdata',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
